### ISSUE TITLE
Не открывается программа из трея.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [RA9OAJ/rexloader#21]
```
Поставил галочку показывать окно по 
двойному клику, но не работает. 
И на мой взгляд вообще было удобнее конечно 
если бы по одному клику открывалось. 
```

Original issue reported on code.google.com by `gorst...@gmail.com` on 23 Oct 2014 at 11:07

**Comment by RA9OAJ** [comment]
Да, есть проблема, но не в моем коде. Видимо что-то в реализации Qt.
Добавил постоянное исправление проблемы.

**Comment by DAP-DarkneSS** [comment]
Пиши `Closes #21`, тогда автоматически баг закроется :)
